### ISSUE TITLE
writing extensible armstrong number

### ISSUE THREAD

**Issue by zainabyousaf** [zainabyousaf/remote_sensing#1]
How to write an armstrong number of any valid length in c++. plz help me.

**Comment by zaeemyousaf** [comment]
### It is pretty easy
//--------------pseudo code
start plucking a digit from either side until it becomes zero
make its cube and add into cumulative sum
at the end of iterations, check its sum and compare it with the original number
it is armstrong if the comparison is true and false otherwise

**Comment by zainabyousaf** [comment]
Thanks zaeem for your kind help.
